In [4]:
import sys
if '/home/ec2-user/sagemaker-pipe-template' not in sys.path:
    sys.path.insert(0, '/home/ec2-user/sagemaker-pipe-template')
import utils, boto3, paths
import pipeline.baseline as baseline
from sagemaker.core.helper.session_helper import Session
import pandas as pd
pd.set_option('display.max_colwidth', None)  # show full text in each cell
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', None)         # don't wrap

In [6]:
region = 'us-east-1'
model_package_group_name='abalone'
model_version=1
data_bucket='omm-test-bucket'
project_path = 'models/abalone'
account='088461143167'

role = utils.get_sm_service_role_arn()
boto_session=boto3.Session(region_name=region)
sm_client = boto_session.client('sagemaker', region_name=region)
sagemaker_session=Session(boto_session=boto_session)
p=paths.Paths(bucket_name='omm-test-bucket', project_name='abalone', model_prefix='abalone')

[06/15/26 20:26:41] INFO     Found credentials from IAM      ]8;id=9493386;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=9493387;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\
                             Role: ec2-1

In [ ]:
baseliner = baseline.Baseliner('abalone-1', p.dq_monitor_dir, p.baseline_file, p.train_file, 'ml.m5.large', sagemaker_session)

,ModelPackageGroupName,ModelPackageGroupArn,CreationTime,ModelPackageGroupStatus
0,abalone,arn:aws:sagemaker:us-east-1:088461143167:model-package-group/abalone,2026-06-15 17:56:51.124000+00:00,Completed

In [6]:
utils.view_model_versions(boto_session)

,ModelPackageGroupName,ModelPackageVersion,ModelPackageArn,ModelPackageDescription,CreationTime,ModelPackageStatus,ModelApprovalStatus,ModelPackageRegistrationType
0,abalone,1,arn:aws:sagemaker:us-east-1:088461143167:model-package/abalone/1,,2026-06-15 17:58:32.074000+00:00,Completed,Approved,Registered

In [5]:
sm_client.update_model_package(ModelPackageArn=f'arn:aws:sagemaker:{region}:{account}:model-package/{model_package_group_name}/{str(model_version)}', ModelApprovalStatus='Approved')

{'ModelPackageArn': 'arn:aws:sagemaker:us-east-1:088461143167:model-package/abalone/1',
 'ResponseMetadata': {'RequestId': 'd4f47167-fe2a-4bf6-b902-f55f060fe46b',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'd4f47167-fe2a-4bf6-b902-f55f060fe46b',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '86',
   'date': 'Mon, 15 Jun 2026 18:00:48 GMT'},
  'RetryAttempts': 0}}