In [6]:
import utils
import pandas as pd
import sagemaker, boto3
pd.set_option('display.max_colwidth', None)  # show full text in each cell
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', None)         # don't wrap

In [8]:
import sagemaker.core.helper.session_helper as session_helper
region = 'us-east-1'

model_package_group_name='abalone'
model_version=1
data_bucket='omm-test-bucket'
project_path = 'models/abalone'
account='088461143167'

role = utils.get_sm_service_role_arn()
boto_session=boto3.Session(region_name=region)
sm_client = boto_session.client('sagemaker', region_name=region)
sagemaker_session = session_helper.Session(boto_session=boto_session)

[06/10/26 00:16:49] INFO     Found credentials from IAM Role: ec2-1                             ]8;id=875403;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=875404;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/ec2-user/.config/sagemaker/config.yaml

In [9]:
utils.view_model_groups(boto_session)

,ModelPackageGroupName,ModelPackageGroupArn,CreationTime,ModelPackageGroupStatus
0,abalone,arn:aws:sagemaker:us-east-1:088461143167:model-package-group/abalone,2026-05-21 17:21:13.441000+00:00,Completed

In [10]:
utils.view_model_versions(boto_session)

,ModelPackageGroupName,ModelPackageVersion,ModelPackageArn,ModelPackageDescription,CreationTime,ModelPackageStatus,ModelApprovalStatus
0,abalone,1,arn:aws:sagemaker:us-east-1:088461143167:model-package/abalone/1,XGBoost model for abalone ring prediction,2026-05-21 17:21:13.782000+00:00,Completed,Approved

In [5]:
# Approve model
sm_client.update_model_package(ModelPackageArn=f'arn:aws:sagemaker:{region}:{account}:model-package/{model_package_group_name}/{str(model_version)}', ModelApprovalStatus='Approved')

{'ModelPackageArn': 'arn:aws:sagemaker:us-east-1:088461143167:model-package/abalone/1',
 'ResponseMetadata': {'RequestId': '84d8cacc-dfb2-4ff4-b911-9518f94251a3',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '84d8cacc-dfb2-4ff4-b911-9518f94251a3',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '86',
   'date': 'Thu, 21 May 2026 17:37:06 GMT'},
  'RetryAttempts': 0}}