In [18]:
import utils, datetime, sagemaker, boto3, importlib
import pandas as pd
import numpy as np
import paths as p
from sagemaker.model_monitor.dataset_format import DatasetFormat
importlib.reload(utils)
pd.set_option('display.max_colwidth', None)  # show full text in each cell
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', None)         # don't wrap

In [3]:
region = 'us-east-1'
role = utils.get_sm_service_role_arn()

data_bucket='omm-test-bucket'
project_path = 'models/abalone'

model_package_group_name='abalone'
model_version=1
target_name='rings'
prediction_name=target_name+'_prediction'
endpoint_name='abalone-endpoint'
model_name = f'{model_package_group_name}-{str(model_version)}'

data_bucket='omm-test-bucket'
project_path = 'models/abalone'
feature_columns = ["length", "diameter", "height", "whole_weight", "shucked_weight", "viscera_weight", "shell_weight", "sex_I", "sex_M", "sex_F"]

boto_session=boto3.Session(region_name=region)
sm_client = boto_session.client('sagemaker', region_name=region)
sagemaker_session = sagemaker.Session(boto_session=boto_session)

## Deploy

In [9]:
model_name, model_arn = utils.create_model_object_from_registry(boto_session, model_package_group_name, model_version)
print(model_name +" "+ model_arn)

using existing model
abalone-1 arn:aws:sagemaker:us-east-1:088461143167:model/abalone-1

In [10]:
utils.deploy_model_endpoint(boto_session, model_name, endpoint_name, p.data_capture_dir, instance_type='ml.m5.large')

creating endpoint config
arn:aws:sagemaker:us-east-1:088461143167:endpoint-config/abalone-endpoint-config
updating endpoint
{'EndpointArn': 'arn:aws:sagemaker:us-east-1:088461143167:endpoint/abalone-endpoint', 'ResponseMetadata': {'RequestId': 'ce5d6cb4-442b-4696-81e2-cdc9fca7019f', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'ce5d6cb4-442b-4696-81e2-cdc9fca7019f', 'strict-transport-security': 'max-age=47304000; includeSubDomains', 'x-frame-options': 'DENY', 'content-security-policy': "frame-ancestors 'none'", 'cache-control': 'no-cache, no-store, must-revalidate', 'x-content-type-options': 'nosniff', 'content-type': 'application/x-amz-json-1.1', 'content-length': '84', 'date': 'Thu, 21 May 2026 17:43:45 GMT'}, 'RetryAttempts': 0}}

## Monitoring

<table class="min-w-full border-collapse text-sm leading-[1.7] whitespace-normal"><thead class="text-left"><tr><th scope="col" class="text-text-100 border-b-0.5 border-border-300/60 py-2 pr-4 align-top font-bold">Class</th><th scope="col" class="text-text-100 border-b-0.5 border-border-300/60 py-2 pr-4 align-top font-bold">Monitors</th></tr></thead><tbody><tr><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top"><code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">DefaultModelMonitor</code></td><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top">Data quality / data drift</td></tr><tr><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top"><code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ModelQualityMonitor</code></td><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top">Model accuracy / prediction quality</td></tr><tr><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top"><code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ModelExplainabilityMonitor</code></td><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top">SHAP feature importance drift</td></tr><tr><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top"><code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ModelBiasMonitor</code></td><td class="border-b-0.5 border-border-300/30 py-2 pr-4 align-top">Bias drift against protected groups</td></tr></tbody></table>

In [36]:
# Delete old monitors
schedules = sm_client.list_monitoring_schedules()
for s in schedules['MonitoringScheduleSummaries']:
    print(s['MonitoringScheduleName'], s['MonitoringScheduleStatus'])

sm_client.delete_monitoring_schedule(MonitoringScheduleName='abalone-model-bias-monitor')
sm_client.delete_monitoring_schedule(MonitoringScheduleName='abalone-model-quality-monitor')
sm_client.delete_monitoring_schedule(MonitoringScheduleName='abalone-data-quality-monitor')

abalone-model-bias-monitor Scheduled
abalone-model-quality-monitor Scheduled
abalone-data-quality-monitor Scheduled

{'ResponseMetadata': {'RequestId': '5e99154f-217e-440a-a1c4-215283860a1a',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': '5e99154f-217e-440a-a1c4-215283860a1a',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'date': 'Thu, 21 May 2026 18:31:14 GMT',
   'content-length': '0'},
  'RetryAttempts': 2}}

In [28]:
baseline_full

,rings_prediction,rings,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,sex_F,sex_I,sex_M
0,8.144435,7,0.410,0.300,0.100,0.2820,0.1255,0.0570,0.0875,0,1,0
1,12.470012,13,0.450,0.360,0.125,0.4995,0.2035,0.1000,0.1700,1,0,0
2,9.323292,11,0.490,0.380,0.135,0.5415,0.2175,0.0950,0.1900,0,0,1
3,10.996564,14,0.430,0.340,0.125,0.3840,0.1375,0.0610,0.1460,0,1,0
4,10.479134,11,0.545,0.450,0.150,0.8795,0.3870,0.1500,0.2625,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
739,10.179646,10,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,0,0,1
740,18.457285,20,0.675,0.545,0.195,1.7345,0.6845,0.3695,0.6050,1,0,0
741,9.217548,8,0.625,0.480,0.185,1.2065,0.5870,0.2900,0.2860,0,0,1
742,7.406839,5,0.400,0.290,0.100,0.2675,0.1205,0.0605,0.0765,0,1,0
743,6.363630,10,0.290,0.225,0.080,0.1295,0.0535,0.0260,0.0450,0,0,1

In [43]:
baseline=pd.read_csv(p.baseline_file, header=0)
baseline_pred=pd.read_csv(p.baseline_pred_file, header=None)
baseline_pred.columns=[prediction_name]
baseline_full = pd.concat([baseline_pred, baseline], axis=1)
baseline_full[target_name] = baseline_full[target_name].astype(float)
baseline_full[prediction_name] = baseline_full[prediction_name].astype(float)


# Data Quality    → input features only
#                   detects: input distribution drift
baseline_full.drop(columns=[target_name, prediction_name]).to_csv(f'{p.dq_monitor_dir}/baseline.csv', index=False, header=True)

# Model Quality   → predictions + ground truth labels
#                   detects: accuracy degradation over time
baseline_full[[target_name, prediction_name]].to_csv(f'{p.mq_monitor_dir}/baseline.csv', index=False, header=True)

# Model Bias      → features + predictions + labels
#                   detects: unfair predictions against subgroups
baseline_full.to_csv(f'{p.mb_monitor_dir}/baseline.csv', index=False, header=True)

# Model Explainability → input features + predictions
#                        detects: feature importance drift
#                        uses SHAP values
baseline_full.drop(columns=[target_name]).to_csv(f'{p.me_monitor_dir}/baseline.csv', index=False, header=True)

### Data Quality

In [32]:
pd.read_csv(f'{p.dq_monitor_dir}/baseline.csv', header=0)

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,sex_F,sex_I,sex_M
0,0.410,0.300,0.100,0.2820,0.1255,0.0570,0.0875,0,1,0
1,0.450,0.360,0.125,0.4995,0.2035,0.1000,0.1700,1,0,0
2,0.490,0.380,0.135,0.5415,0.2175,0.0950,0.1900,0,0,1
3,0.430,0.340,0.125,0.3840,0.1375,0.0610,0.1460,0,1,0
4,0.545,0.450,0.150,0.8795,0.3870,0.1500,0.2625,0,0,1
...,...,...,...,...,...,...,...,...,...,...
739,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,0,0,1
740,0.675,0.545,0.195,1.7345,0.6845,0.3695,0.6050,1,0,0
741,0.625,0.480,0.185,1.2065,0.5870,0.2900,0.2860,0,0,1
742,0.400,0.290,0.100,0.2675,0.1205,0.0605,0.0765,0,1,0
743,0.290,0.225,0.080,0.1295,0.0535,0.0260,0.0450,0,0,1

In [33]:
data_quality_monitor = sagemaker.model_monitor.DefaultModelMonitor(
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    volume_size_in_gb=20,
    max_runtime_in_seconds=1800,
    sagemaker_session=sagemaker_session
)

data_quality_monitor.suggest_baseline(
    baseline_dataset=f'{p.dq_monitor_dir}/baseline.csv',
    dataset_format=DatasetFormat.csv(header=True),
    output_s3_uri=f"{p.dq_monitor_dir}/info",
    wait=True,
    logs=False
)

INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: .
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker:Creating processing-job with name baseline-suggestion-job-2026-05-21-18-24-32-312

...........................................................!

In [37]:
data_quality_monitor.create_monitoring_schedule(
    monitor_schedule_name='abalone-data-quality-monitor',
    endpoint_input='abalone-endpoint',
    output_s3_uri=f'{p.dq_monitor_dir}/reports',
    statistics=data_quality_monitor.baseline_statistics(),
    constraints=data_quality_monitor.suggested_constraints(),
    schedule_cron_expression=sagemaker.model_monitor.CronExpressionGenerator.hourly()
)
# transform job has no data capture but instead has separate files for inputs and ouputs
# monitor.create_monitoring_schedule(
#     monitor_schedule_name='abalone-batch-monitor',
#     batch_transform_input=sagemaker.model_monitor.BatchTransformInput(
#         data_captured_destination_s3_uri=f's3://{data_bucket}/batch-output/', # predictions
#         dataset_format=DatasetFormat.csv(header=False),
#         local_path='/opt/ml/processing/input' # also need to point at input features separately
#     ),
#     output_s3_uri=f's3://{data_bucket}/model-monitor/reports',
#     statistics=monitor.baseline_statistics(),
#     constraints=monitor.suggested_constraints(),
#     schedule_cron_expression=sagemaker.model_monitor.CronExpressionGenerator.hourly()
# )

INFO:sagemaker.model_monitor.model_monitoring:Creating Monitoring Schedule with name: abalone-data-quality-monitor

### Model Quality

In [38]:
model_quality_monitor = sagemaker.model_monitor.ModelQualityMonitor(
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    volume_size_in_gb=20,
    max_runtime_in_seconds=1800,
    sagemaker_session=sagemaker_session
)

model_quality_monitor.suggest_baseline(
    baseline_dataset=f'{p.mq_monitor_dir}/baseline.csv',
    dataset_format=DatasetFormat.csv(header=True),
    output_s3_uri=f'{p.mq_monitor_dir}/info',
    problem_type='Regression',
    inference_attribute=prediction_name,   # target column header (named by PySpark)
    ground_truth_attribute=target_name, # output column header (only 1 output)
    wait=True,
    logs=False
)

INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: .
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker:Creating processing-job with name baseline-suggestion-job-2026-05-21-18-31-34-226

...........................................................!

In [39]:
model_quality_monitor.create_monitoring_schedule(
    monitor_schedule_name='abalone-model-quality-monitor',
    endpoint_input=sagemaker.model_monitor.EndpointInput(
        endpoint_name=endpoint_name,
        destination='/opt/ml/processing/input/endpoint',
        inference_attribute=prediction_name  # column index of prediction in output
    ),
    ground_truth_input=p.ground_truth_dir,
    problem_type='Regression',
    output_s3_uri=f'{p.mq_monitor_dir}/reports',
    constraints=model_quality_monitor.suggested_constraints(),
    schedule_cron_expression=sagemaker.model_monitor.CronExpressionGenerator.hourly()
)

INFO:sagemaker.model_monitor.model_monitoring:Creating Monitoring Schedule with name: abalone-model-quality-monitor

### Model Bias

In [42]:
pd.read_csv(f'{p.mb_monitor_dir}/baseline.csv').dtypes

rings_prediction    float64
rings                 int64
length              float64
diameter            float64
height              float64
whole_weight        float64
shucked_weight      float64
viscera_weight      float64
shell_weight        float64
sex_F                 int64
sex_I                 int64
sex_M                 int64
dtype: object

In [44]:
endpoint_config_name = sm_client.describe_endpoint(EndpointName=endpoint_name)['EndpointConfigName']
model_name = sm_client.describe_endpoint_config(EndpointConfigName=endpoint_config_name)['ProductionVariants'][0]['ModelName']

model_bias_monitor = sagemaker.model_monitor.ModelBiasMonitor(
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    volume_size_in_gb=20,
    max_runtime_in_seconds=1800,
    sagemaker_session=sagemaker_session
)

model_bias_monitor.suggest_baseline(
    data_config=sagemaker.clarify.DataConfig(
        s3_data_input_path=f'{p.mb_monitor_dir}/baseline.csv',
        s3_output_path=f'{p.mb_monitor_dir}/info',
        dataset_type = 'text/csv',
        label=target_name,
        predicted_label=prediction_name, 
    ),
    bias_config=sagemaker.clarify.BiasConfig(facet_name='sex_F', label_values_or_threshold=[7], facet_values_or_threshold=[0.5]),
    model_config=sagemaker.clarify.ModelConfig(
        model_name=model_name,
        instance_type='ml.m5.large',
        instance_count=1,
        accept_type='text/csv',
        content_type='text/csv'
    ),
    # model_predicted_label_config=sagemaker.clarify.ModelPredictedLabelConfig(
    #     probability_threshold=0.5  # threshold to convert float prediction to binary label
    # ), 
    wait=True,
    logs=False
)

INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: 1.0.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: 1.0.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker.clarify:Analysis Config: {'dataset_type': 'text/csv', 'label': 'rings', 'predicted_label': 'rings_prediction', 'label_values_or_threshold': [7], 'facet': [{'name_or_index': 'sex_F', 'value_or_threshold': [0.5]}], 'methods': {'report': {'name': 'report', 'title': 'Analysis Report'}, 'pre_training_bias': {'methods': 'all'}, 'post_training_bias': {'methods': 'all'}}, 'predictor': {'model_name': 'abalone-1', 'instance_type': 'ml.m5.large', 'initial_instance_count': 1, 'accept_type': 'text/csv', 'content_type': 'text/csv'}}
INFO:sagemaker:Creating processing-job with name baseline-suggestion-job-2026-05-21-18-49-35-779

...........................................................!

In [45]:
model_bias_monitor.create_monitoring_schedule(
    monitor_schedule_name='abalone-model-bias-monitor',
    endpoint_input=sagemaker.model_monitor.EndpointInput(
        endpoint_name=endpoint_name,
        destination='/opt/ml/processing/input/endpoint',
        inference_attribute='0'
    ),
    ground_truth_input=p.ground_truth_dir,
    output_s3_uri=f'{p.mb_monitor_dir}/reports',
    schedule_cron_expression=sagemaker.model_monitor.CronExpressionGenerator.hourly()
)

INFO:sagemaker.model_monitor.clarify_model_monitoring:Uploading analysis config to {s3_uri}.
INFO:sagemaker.model_monitor.model_monitoring:Creating Monitoring Schedule with name: abalone-model-bias-monitor

### Predict

In [23]:
test_X=pd.read_csv(p.test_X_file, index_col=0, header=None)
test_X.index.name = None
batch_in_df = test_X.iloc[0:2]
batch_in_df

         1     2      3       4       5      6      7   8   9   10
4163  0.255  0.19  0.070  0.0815  0.0280  0.016  0.031   0   1   0
1270  0.630  0.48  0.145  1.0115  0.4235  0.237  0.305   0   0   1

In [ ]:
# get batch_in_event_ids and save indexless batch_in like X
batch_in_event_ids = batch_in_df.index.to_series()

#batch_in_file=f"{p.batch_in_dir}/{datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H-%M-%S')}"
batch_in_dir=f's3://omm-test-bucket/models/abalone/data/batch-input'
time_string=datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H-%M-%S')
batch_in_file=f"{batch_in_dir}/{time_string}_X.csv"
event_in_file=f"{batch_in_dir}/{time_string}_event_ids.csv"
predictions_file=f"{p.batch_out_dir}/{time_string}_X.csv.out"

batch_in_df.to_csv(batch_in_file, index=False, header=False)
batch_in_df.index.to_series().to_csv(event_in_file, index=False, header=False)

In [29]:
transformer = sagemaker.transformer.Transformer(
    model_name=model_name,
    instance_count=1,
    instance_type='ml.m5.large',
    output_path=p.batch_out_dir+'/',
    accept='text/csv',
    assemble_with='Line',
    sagemaker_session=sagemaker_session
)
transformer.transform(
    data=batch_in_file,
    content_type='text/csv',
    split_type='Line',
    wait=True,
    logs=False
)

# Join results with event IDs after
predictions = pd.read_csv(predictions_file, header=None, names=['prediction'])

INFO:sagemaker:Creating transform job with name: sagemaker-xgboost-2026-05-21-21-32-19-737

.................................................................!

In [ ]:
results = pd.DataFrame({
    'event_id': event_ids,
    'prediction': predictions['prediction']
})

In [46]:
# JSON input
test_X=pd.read_csv(p.test_X_file, index_col=0, header=None)
test_X.index.name = None
test_X.columns = feature_columns
test_dicts=test_X.reset_index().rename(columns={'index': 'id'}).to_dict(orient='records')
model_dict_input=[{k: v for k, v in d.items() if k != target_name} for d in test_dicts]
model_dict_input=[{k: v for k, v in d.items() if k != target_name} for d in test_dicts]

records_to_predict = model_dict_input[0:2]
print(model_dict_input)

[{'id': 4163, 'length': 0.255, 'diameter': 0.19, 'height': 0.07, 'whole_weight': 0.0815, 'shucked_weight': 0.028, 'viscera_weight': 0.016, 'shell_weight': 0.031, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1270, 'length': 0.63, 'diameter': 0.48, 'height': 0.145, 'whole_weight': 1.0115, 'shucked_weight': 0.4235, 'viscera_weight': 0.237, 'shell_weight': 0.305, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3274, 'length': 0.5, 'diameter': 0.385, 'height': 0.145, 'whole_weight': 0.7615, 'shucked_weight': 0.246, 'viscera_weight': 0.195, 'shell_weight': 0.204, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3897, 'length': 0.41, 'diameter': 0.325, 'height': 0.105, 'whole_weight': 0.361, 'shucked_weight': 0.1605, 'viscera_weight': 0.0665, 'shell_weight': 0.103, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3864, 'length': 0.695, 'diameter': 0.535, 'height': 0.2, 'whole_weight': 1.5855, 'shucked_weight': 0.667, 'viscera_weight': 0.334, 'shell_weight': 0.471, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1694, 'length': 0.335, 'diameter': 0.25, 'height': 0.075, 'whole_weight': 0.1825, 'shucked_weight': 0.0705, 'viscera_weight': 0.044, 'shell_weight': 0.055, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4337, 'length': 0.515, 'diameter': 0.4, 'height': 0.135, 'whole_weight': 0.636, 'shucked_weight': 0.3055, 'viscera_weight': 0.1215, 'shell_weight': 0.1855, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4677, 'length': 0.56, 'diameter': 0.46, 'height': 0.18, 'whole_weight': 0.97, 'shucked_weight': 0.342, 'viscera_weight': 0.196, 'shell_weight': 0.355, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 4689, 'length': 0.635, 'diameter': 0.48, 'height': 0.235, 'whole_weight': 1.064, 'shucked_weight': 0.413, 'viscera_weight': 0.228, 'shell_weight': 0.36, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 843, 'length': 0.47, 'diameter': 0.385, 'height': 0.135, 'whole_weight': 0.5895, 'shucked_weight': 0.2765, 'viscera_weight': 0.12, 'shell_weight': 0.17, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4902, 'length': 0.625, 'diameter': 0.48, 'height': 0.16, 'whole_weight': 1.2415, 'shucked_weight': 0.6575, 'viscera_weight': 0.2625, 'shell_weight': 0.2785, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 2042, 'length': 0.425, 'diameter': 0.31, 'height': 0.09, 'whole_weight': 0.301, 'shucked_weight': 0.1385, 'viscera_weight': 0.065, 'shell_weight': 0.08, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3346, 'length': 0.44, 'diameter': 0.335, 'height': 0.11, 'whole_weight': 0.3885, 'shucked_weight': 0.175, 'viscera_weight': 0.0835, 'shell_weight': 0.111, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 807, 'length': 0.38, 'diameter': 0.275, 'height': 0.1, 'whole_weight': 0.2255, 'shucked_weight': 0.08, 'viscera_weight': 0.049, 'shell_weight': 0.085, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3821, 'length': 0.55, 'diameter': 0.405, 'height': 0.15, 'whole_weight': 0.6755, 'shucked_weight': 0.3015, 'viscera_weight': 0.1465, 'shell_weight': 0.21, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1918, 'length': 0.565, 'diameter': 0.45, 'height': 0.175, 'whole_weight': 1.0095, 'shucked_weight': 0.447, 'viscera_weight': 0.2375, 'shell_weight': 0.2645, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 2754, 'length': 0.665, 'diameter': 0.525, 'height': 0.18, 'whole_weight': 1.429, 'shucked_weight': 0.6715, 'viscera_weight': 0.29, 'shell_weight': 0.4, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 1151, 'length': 0.63, 'diameter': 0.515, 'height': 0.16, 'whole_weight': 1.016, 'shucked_weight': 0.4215, 'viscera_weight': 0.244, 'shell_weight': 0.355, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 831, 'length': 0.39, 'diameter': 0.295, 'height': 0.095, 'whole_weight': 0.203, 'shucked_weight': 0.0875, 'viscera_weight': 0.045, 'shell_weight': 0.075, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 422, 'length': 0.49, 'diameter': 0.39, 'height': 0.135, 'whole_weight': 0.5785, 'shucked_weight': 0.2465, 'viscera_weight': 0.123, 'shell_weight': 0.2, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 491, 'length': 0.58, 'diameter': 0.46, 'height': 0.13, 'whole_weight': 0.921, 'shucked_weight': 0.357, 'viscera_weight': 0.181, 'shell_weight': 0.29, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3464, 'length': 0.615, 'diameter': 0.45, 'height': 0.15, 'whole_weight': 1.198, 'shucked_weight': 0.707, 'viscera_weight': 0.2095, 'shell_weight': 0.2505, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 625, 'length': 0.525, 'diameter': 0.405, 'height': 0.16, 'whole_weight': 0.658, 'shucked_weight': 0.2655, 'viscera_weight': 0.1125, 'shell_weight': 0.225, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1945, 'length': 0.605, 'diameter': 0.48, 'height': 0.17, 'whole_weight': 1.1835, 'shucked_weight': 0.582, 'viscera_weight': 0.2365, 'shell_weight': 0.317, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3102, 'length': 0.535, 'diameter': 0.435, 'height': 0.155, 'whole_weight': 0.8915, 'shucked_weight': 0.3415, 'viscera_weight': 0.177, 'shell_weight': 0.25, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 2478, 'length': 0.625, 'diameter': 0.485, 'height': 0.175, 'whole_weight': 1.362, 'shucked_weight': 0.6765, 'viscera_weight': 0.2615, 'shell_weight': 0.3705, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3074, 'length': 0.33, 'diameter': 0.265, 'height': 0.09, 'whole_weight': 0.18, 'shucked_weight': 0.068, 'viscera_weight': 0.036, 'shell_weight': 0.06, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3132, 'length': 0.56, 'diameter': 0.43, 'height': 0.125, 'whole_weight': 0.8025, 'shucked_weight': 0.313, 'viscera_weight': 0.1715, 'shell_weight': 0.263, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 4125, 'length': 0.585, 'diameter': 0.475, 'height': 0.185, 'whole_weight': 0.8575, 'shucked_weight': 0.3465, 'viscera_weight': 0.1785, 'shell_weight': 0.275, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3196, 'length': 0.505, 'diameter': 0.375, 'height': 0.115, 'whole_weight': 0.5895, 'shucked_weight': 0.2635, 'viscera_weight': 0.12, 'shell_weight': 0.167, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3758, 'length': 0.72, 'diameter': 0.58, 'height': 0.19, 'whole_weight': 2.0885, 'shucked_weight': 0.9955, 'viscera_weight': 0.478, 'shell_weight': 0.5305, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4947, 'length': 0.585, 'diameter': 0.455, 'height': 0.17, 'whole_weight': 0.9945, 'shucked_weight': 0.4255, 'viscera_weight': 0.263, 'shell_weight': 0.2845, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1864, 'length': 0.42, 'diameter': 0.31, 'height': 0.095, 'whole_weight': 0.279, 'shucked_weight': 0.1255, 'viscera_weight': 0.051, 'shell_weight': 0.088, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4105, 'length': 0.705, 'diameter': 0.555, 'height': 0.2, 'whole_weight': 1.4685, 'shucked_weight': 0.4715, 'viscera_weight': 0.3235, 'shell_weight': 0.52, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 2497, 'length': 0.645, 'diameter': 0.51, 'height': 0.16, 'whole_weight': 1.33, 'shucked_weight': 0.6665, 'viscera_weight': 0.309, 'shell_weight': 0.317, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4845, 'length': 0.515, 'diameter': 0.39, 'height': 0.12, 'whole_weight': 0.6125, 'shucked_weight': 0.302, 'viscera_weight': 0.1365, 'shell_weight': 0.1415, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 17, 'length': 0.44, 'diameter': 0.34, 'height': 0.1, 'whole_weight': 0.451, 'shucked_weight': 0.188, 'viscera_weight': 0.087, 'shell_weight': 0.13, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 805, 'length': 0.45, 'diameter': 0.32, 'height': 0.1, 'whole_weight': 0.381, 'shucked_weight': 0.1705, 'viscera_weight': 0.075, 'shell_weight': 0.115, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4889, 'length': 0.7, 'diameter': 0.545, 'height': 0.215, 'whole_weight': 1.9125, 'shucked_weight': 0.8825, 'viscera_weight': 0.4385, 'shell_weight': 0.506, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3158, 'length': 0.405, 'diameter': 0.325, 'height': 0.11, 'whole_weight': 0.3575, 'shucked_weight': 0.145, 'viscera_weight': 0.0725, 'shell_weight': 0.11, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1374, 'length': 0.45, 'diameter': 0.335, 'height': 0.14, 'whole_weight': 0.4625, 'shucked_weight': 0.164, 'viscera_weight': 0.076, 'shell_weight': 0.15, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 2921, 'length': 0.565, 'diameter': 0.425, 'height': 0.1, 'whole_weight': 0.7145, 'shucked_weight': 0.3055, 'viscera_weight': 0.166, 'shell_weight': 0.18, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3337, 'length': 0.295, 'diameter': 0.22, 'height': 0.07, 'whole_weight': 0.126, 'shucked_weight': 0.0515, 'viscera_weight': 0.0275, 'shell_weight': 0.035, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1964, 'length': 0.65, 'diameter': 0.5, 'height': 0.19, 'whole_weight': 1.464, 'shucked_weight': 0.6415, 'viscera_weight': 0.339, 'shell_weight': 0.4245, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1784, 'length': 0.59, 'diameter': 0.455, 'height': 0.145, 'whole_weight': 1.063, 'shucked_weight': 0.5155, 'viscera_weight': 0.2445, 'shell_weight': 0.25, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1721, 'length': 0.45, 'diameter': 0.345, 'height': 0.11, 'whole_weight': 0.47, 'shucked_weight': 0.2355, 'viscera_weight': 0.0855, 'shell_weight': 0.1135, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1606, 'length': 0.365, 'diameter': 0.275, 'height': 0.135, 'whole_weight': 0.24, 'shucked_weight': 0.108, 'viscera_weight': 0.0445, 'shell_weight': 0.0735, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3867, 'length': 0.73, 'diameter': 0.55, 'height': 0.205, 'whole_weight': 1.908, 'shucked_weight': 0.5415, 'viscera_weight': 0.3565, 'shell_weight': 0.5965, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 438, 'length': 0.39, 'diameter': 0.3, 'height': 0.09, 'whole_weight': 0.3055, 'shucked_weight': 0.143, 'viscera_weight': 0.0645, 'shell_weight': 0.085, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4766, 'length': 0.525, 'diameter': 0.41, 'height': 0.115, 'whole_weight': 0.7745, 'shucked_weight': 0.416, 'viscera_weight': 0.163, 'shell_weight': 0.18, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1261, 'length': 0.53, 'diameter': 0.415, 'height': 0.175, 'whole_weight': 0.7395, 'shucked_weight': 0.261, 'viscera_weight': 0.1395, 'shell_weight': 0.2645, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 810, 'length': 0.615, 'diameter': 0.48, 'height': 0.165, 'whole_weight': 1.1615, 'shucked_weight': 0.513, 'viscera_weight': 0.301, 'shell_weight': 0.305, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3166, 'length': 0.175, 'diameter': 0.135, 'height': 0.04, 'whole_weight': 0.0305, 'shucked_weight': 0.011, 'viscera_weight': 0.0075, 'shell_weight': 0.01, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3626, 'length': 0.59, 'diameter': 0.485, 'height': 0.155, 'whole_weight': 1.0785, 'shucked_weight': 0.4535, 'viscera_weight': 0.2435, 'shell_weight': 0.31, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3437, 'length': 0.51, 'diameter': 0.385, 'height': 0.15, 'whole_weight': 0.625, 'shucked_weight': 0.3095, 'viscera_weight': 0.119, 'shell_weight': 0.1725, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3515, 'length': 0.405, 'diameter': 0.305, 'height': 0.1, 'whole_weight': 0.268, 'shucked_weight': 0.1145, 'viscera_weight': 0.053, 'shell_weight': 0.085, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 889, 'length': 0.53, 'diameter': 0.415, 'height': 0.14, 'whole_weight': 0.724, 'shucked_weight': 0.3105, 'viscera_weight': 0.1675, 'shell_weight': 0.205, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3377, 'length': 0.585, 'diameter': 0.45, 'height': 0.16, 'whole_weight': 0.9045, 'shucked_weight': 0.405, 'viscera_weight': 0.2215, 'shell_weight': 0.2335, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 683, 'length': 0.535, 'diameter': 0.405, 'height': 0.185, 'whole_weight': 0.8345, 'shucked_weight': 0.3175, 'viscera_weight': 0.1725, 'shell_weight': 0.29, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 869, 'length': 0.595, 'diameter': 0.475, 'height': 0.16, 'whole_weight': 1.3175, 'shucked_weight': 0.408, 'viscera_weight': 0.234, 'shell_weight': 0.58, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 1094, 'length': 0.55, 'diameter': 0.41, 'height': 0.125, 'whole_weight': 0.7605, 'shucked_weight': 0.2505, 'viscera_weight': 0.1635, 'shell_weight': 0.195, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 790, 'length': 0.33, 'diameter': 0.255, 'height': 0.08, 'whole_weight': 0.205, 'shucked_weight': 0.0895, 'viscera_weight': 0.0395, 'shell_weight': 0.055, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 2450, 'length': 0.605, 'diameter': 0.47, 'height': 0.145, 'whole_weight': 0.8025, 'shucked_weight': 0.379, 'viscera_weight': 0.2265, 'shell_weight': 0.22, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4866, 'length': 0.555, 'diameter': 0.43, 'height': 0.125, 'whole_weight': 0.7005, 'shucked_weight': 0.3395, 'viscera_weight': 0.1355, 'shell_weight': 0.2095, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4148, 'length': 0.41, 'diameter': 0.3, 'height': 0.1, 'whole_weight': 0.301, 'shucked_weight': 0.124, 'viscera_weight': 0.069, 'shell_weight': 0.09, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 725, 'length': 0.49, 'diameter': 0.36, 'height': 0.11, 'whole_weight': 0.5005, 'shucked_weight': 0.161, 'viscera_weight': 0.107, 'shell_weight': 0.195, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 1483, 'length': 0.28, 'diameter': 0.205, 'height': 0.1, 'whole_weight': 0.1165, 'shucked_weight': 0.0545, 'viscera_weight': 0.0285, 'shell_weight': 0.03, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 1831, 'length': 0.69, 'diameter': 0.505, 'height': 0.2, 'whole_weight': 1.872, 'shucked_weight': 0.893, 'viscera_weight': 0.4015, 'shell_weight': 0.48, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3960, 'length': 0.45, 'diameter': 0.355, 'height': 0.12, 'whole_weight': 0.3955, 'shucked_weight': 0.147, 'viscera_weight': 0.0765, 'shell_weight': 0.145, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 3576, 'length': 0.62, 'diameter': 0.48, 'height': 0.165, 'whole_weight': 1.0125, 'shucked_weight': 0.5325, 'viscera_weight': 0.4365, 'shell_weight': 0.324, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 2984, 'length': 0.27, 'diameter': 0.19, 'height': 0.08, 'whole_weight': 0.081, 'shucked_weight': 0.0265, 'viscera_weight': 0.0195, 'shell_weight': 0.03, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4122, 'length': 0.45, 'diameter': 0.35, 'height': 0.125, 'whole_weight': 0.4435, 'shucked_weight': 0.185, 'viscera_weight': 0.09, 'shell_weight': 0.145, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 945, 'length': 0.575, 'diameter': 0.46, 'height': 0.165, 'whole_weight': 1.124, 'shucked_weight': 0.2985, 'viscera_weight': 0.1785, 'shell_weight': 0.44, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 2366, 'length': 0.5, 'diameter': 0.4, 'height': 0.12, 'whole_weight': 0.616, 'shucked_weight': 0.261, 'viscera_weight': 0.143, 'shell_weight': 0.1935, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1902, 'length': 0.525, 'diameter': 0.395, 'height': 0.12, 'whole_weight': 0.608, 'shucked_weight': 0.297, 'viscera_weight': 0.1395, 'shell_weight': 0.1405, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 2968, 'length': 0.55, 'diameter': 0.43, 'height': 0.16, 'whole_weight': 0.9295, 'shucked_weight': 0.317, 'viscera_weight': 0.1735, 'shell_weight': 0.355, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 2447, 'length': 0.6, 'diameter': 0.47, 'height': 0.16, 'whole_weight': 1.194, 'shucked_weight': 0.5625, 'viscera_weight': 0.3045, 'shell_weight': 0.2635, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 1840, 'length': 0.195, 'diameter': 0.15, 'height': 0.045, 'whole_weight': 0.0375, 'shucked_weight': 0.018, 'viscera_weight': 0.006, 'shell_weight': 0.011, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 4179, 'length': 0.575, 'diameter': 0.435, 'height': 0.13, 'whole_weight': 1.0105, 'shucked_weight': 0.368, 'viscera_weight': 0.222, 'shell_weight': 0.32, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4748, 'length': 0.72, 'diameter': 0.575, 'height': 0.195, 'whole_weight': 2.1505, 'shucked_weight': 1.0745, 'viscera_weight': 0.382, 'shell_weight': 0.585, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 70, 'length': 0.555, 'diameter': 0.425, 'height': 0.13, 'whole_weight': 0.7665, 'shucked_weight': 0.264, 'viscera_weight': 0.168, 'shell_weight': 0.275, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4412, 'length': 0.69, 'diameter': 0.53, 'height': 0.19, 'whole_weight': 1.5955, 'shucked_weight': 0.678, 'viscera_weight': 0.331, 'shell_weight': 0.48, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4408, 'length': 0.655, 'diameter': 0.505, 'height': 0.165, 'whole_weight': 1.27, 'shucked_weight': 0.6035, 'viscera_weight': 0.262, 'shell_weight': 0.335, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4873, 'length': 0.595, 'diameter': 0.475, 'height': 0.155, 'whole_weight': 0.984, 'shucked_weight': 0.4865, 'viscera_weight': 0.184, 'shell_weight': 0.2755, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1962, 'length': 0.645, 'diameter': 0.53, 'height': 0.195, 'whole_weight': 1.39, 'shucked_weight': 0.6465, 'viscera_weight': 0.2945, 'shell_weight': 0.3735, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 149, 'length': 0.17, 'diameter': 0.13, 'height': 0.095, 'whole_weight': 0.03, 'shucked_weight': 0.013, 'viscera_weight': 0.008, 'shell_weight': 0.01, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3453, 'length': 0.585, 'diameter': 0.45, 'height': 0.15, 'whole_weight': 0.938, 'shucked_weight': 0.467, 'viscera_weight': 0.203, 'shell_weight': 0.225, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3618, 'length': 0.54, 'diameter': 0.42, 'height': 0.14, 'whole_weight': 0.8035, 'shucked_weight': 0.38, 'viscera_weight': 0.1805, 'shell_weight': 0.21, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 633, 'length': 0.47, 'diameter': 0.36, 'height': 0.13, 'whole_weight': 0.5225, 'shucked_weight': 0.198, 'viscera_weight': 0.1065, 'shell_weight': 0.165, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3729, 'length': 0.63, 'diameter': 0.485, 'height': 0.185, 'whole_weight': 1.167, 'shucked_weight': 0.548, 'viscera_weight': 0.2485, 'shell_weight': 0.34, 'sex_I': 1, 'sex_M': 0, 'sex_F': 0}, {'id': 3194, 'length': 0.62, 'diameter': 0.485, 'height': 0.17, 'whole_weight': 1.208, 'shucked_weight': 0.4805, 'viscera_weight': 0.3045, 'shell_weight': 0.33, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 1564, 'length': 0.465, 'diameter': 0.35, 'height': 0.14, 'whole_weight': 0.5755, 'shucked_weight': 0.2015, 'viscera_weight': 0.1505, 'shell_weight': 0.19, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 4796, 'length': 0.61, 'diameter': 0.475, 'height': 0.15, 'whole_weight': 1.142, 'shucked_weight': 0.62, 'viscera_weight': 0.237, 'shell_weight': 0.245, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 443, 'length': 0.395, 'diameter': 0.295, 'height': 0.1, 'whole_weight': 0.2715, 'shucked_weight': 0.134, 'viscera_weight': 0.0325, 'shell_weight': 0.085, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 549, 'length': 0.555, 'diameter': 0.425, 'height': 0.18, 'whole_weight': 0.875, 'shucked_weight': 0.3695, 'viscera_weight': 0.2005, 'shell_weight': 0.255, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 2341, 'length': 0.41, 'diameter': 0.3, 'height': 0.09, 'whole_weight': 0.28, 'shucked_weight': 0.141, 'viscera_weight': 0.0575, 'shell_weight': 0.075, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 463, 'length': 0.22, 'diameter': 0.165, 'height': 0.055, 'whole_weight': 0.0545, 'shucked_weight': 0.0215, 'viscera_weight': 0.012, 'shell_weight': 0.02, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 2486, 'length': 0.635, 'diameter': 0.5, 'height': 0.17, 'whole_weight': 1.4345, 'shucked_weight': 0.611, 'viscera_weight': 0.309, 'shell_weight': 0.418, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 298, 'length': 0.49, 'diameter': 0.395, 'height': 0.14, 'whole_weight': 0.549, 'shucked_weight': 0.2215, 'viscera_weight': 0.1275, 'shell_weight': 0.15, 'sex_I': 0, 'sex_M': 0, 'sex_F': 1}, {'id': 1222, 'length': 0.36, 'diameter': 0.275, 'height': 0.095, 'whole_weight': 0.217, 'shucked_weight': 0.084, 'viscera_weight': 0.0435, 'shell_weight': 0.09, 'sex_I': 0, 'sex_M': 1, 'sex_F': 0}, {'id': 3841, 'length': 0.61, 'diameter': 0.495, 'height': 0.16, 'whole_weight': 1.089, 'shucked_weight': 0.469, 'viscera_weight': 0.198, 'shell_weight': 0.384, 'sex_I': 1, 'sex_M': 0, 

In [47]:
def predict_request(boto_session, records, featue_columns):
    sm_runtime = boto_session.client('sagemaker-runtime')

    for r in records:
        # row to csv
        row_values=[]
        for column in featue_columns:
            row_values.append(str(r[column]))
        row_csv=','.join(row_values)

        response = sm_runtime.invoke_endpoint(EndpointName=endpoint_name, ContentType='text/csv', Body=row_csv.encode('utf-8'), InferenceId=str(r["id"]))
        print(response)
predict_request(boto_session, records_to_predict, feature_columns)

{'ResponseMetadata': {'RequestId': 'b95ef36e-401b-42a9-9b15-bbebe90003b2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'b95ef36e-401b-42a9-9b15-bbebe90003b2', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Thu, 21 May 2026 19:00:37 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '18', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7fb527977d30>}
{'ResponseMetadata': {'RequestId': '212e28f5-662c-45b3-8dc4-8194f29f6d7c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '212e28f5-662c-45b3-8dc4-8194f29f6d7c', 'x-amzn-invoked-production-variant': 'AllTraffic', 'date': 'Thu, 21 May 2026 19:00:37 GMT', 'content-type': 'text/csv; charset=utf-8', 'content-length': '19', 'connection': 'keep-alive'}, 'RetryAttempts': 0}, 'ContentType': 'text/csv; charset=utf-8', 'InvokedProductionVariant': 'AllTraffic', 'Body': <botocore.response.StreamingBody object at 0x7fb527977be0>}

## Ground Truth

In [ ]:
test_y=pd.read_csv(p.test_y_file, index_col=0, header=None)
test_y.index.name = None
test_y.columns=[target_name]
test_dicts=test_y.reset_index().rename(columns={'index': 'id'}).to_dict(orient='records')
ground_truth=[{"value":d[target_name], "event_id":d["id"]} for d in test_dicts]

ground_truths_to_submit = ground_truth[0:2]
print(ground_truth)

# s3://omm-test-bucket/models/abalone/data/capture/abalone-endpoint/AllTraffic/2026/05/21/19/00-37-322-08eeba9c-04c8-4327-8238-d1511d5962a5.jsonl
# {
#   "captureData": {
#     "endpointInput": {
#       "observedContentType": "text/csv",
#       "mode": "INPUT",
#       "data": "MC4yNTUsMC4xOSwwLjA3LDAuMDgxNSwwLjAyOCwwLjAxNiwwLjAzMSwwLDEsMA==",
#       "encoding": "BASE64"
#     },
#     "endpointOutput": {
#       "observedContentType": "text/csv; charset=utf-8",
#       "mode": "OUTPUT",
#       "data": "NS45MDg2NjQyMjY1MzE5ODIK",
#       "encoding": "BASE64"
#     }
#   },
#   "eventMetadata": {
#     "eventId": "b95ef36e-401b-42a9-9b15-bbebe90003b2",
#     "inferenceId": "4163",
#     "inferenceTime": "2026-05-21T19:00:37Z"
#   },
#   "eventVersion": "0"
# }
# {
#   "captureData": {
#     "endpointInput": {
#       "observedContentType": "text/csv",
#       "mode": "INPUT",
#       "data": "MC42MywwLjQ4LDAuMTQ1LDEuMDExNSwwLjQyMzUsMC4yMzcsMC4zMDUsMCwwLDE=",
#       "encoding": "BASE64"
#     },
#     "endpointOutput": {
#       "observedContentType": "text/csv; charset=utf-8",
#       "mode": "OUTPUT",
#       "data": "MTEuMjg3MjAyODM1MDgzMDA4Cg==",
#       "encoding": "BASE64"
#     }
#   },
#   "eventMetadata": {
#     "eventId": "212e28f5-662c-45b3-8dc4-8194f29f6d7c",
#     "inferenceId": "1270",
#     "inferenceTime": "2026-05-21T19:00:37Z"
#   },
#   "eventVersion": "0"
# }

[{'value': 5, 'event_id': 4163}, {'value': 12, 'event_id': 1270}, {'value': 14, 'event_id': 3274}, {'value': 8, 'event_id': 3897}, {'value': 11, 'event_id': 3864}, {'value': 7, 'event_id': 1694}, {'value': 9, 'event_id': 4337}, {'value': 12, 'event_id': 4677}, {'value': 16, 'event_id': 4689}, {'value': 8, 'event_id': 843}, {'value': 9, 'event_id': 4902}, {'value': 7, 'event_id': 2042}, {'value': 7, 'event_id': 3346}, {'value': 10, 'event_id': 807}, {'value': 10, 'event_id': 3821}, {'value': 9, 'event_id': 1918}, {'value': 12, 'event_id': 2754}, {'value': 19, 'event_id': 1151}, {'value': 7, 'event_id': 831}, {'value': 13, 'event_id': 422}, {'value': 13, 'event_id': 491}, {'value': 7, 'event_id': 3464}, {'value': 12, 'event_id': 625}, {'value': 10, 'event_id': 1945}, {'value': 13, 'event_id': 3102}, {'value': 10, 'event_id': 2478}, {'value': 6, 'event_id': 3074}, {'value': 13, 'event_id': 3132}, {'value': 12, 'event_id': 4125}, {'value': 10, 'event_id': 3196}, {'value': 13, 'event_id': 3758}, {'value': 11, 'event_id': 4947}, {'value': 6, 'event_id': 1864}, {'value': 19, 'event_id': 4105}, {'value': 9, 'event_id': 2497}, {'value': 8, 'event_id': 4845}, {'value': 10, 'event_id': 17}, {'value': 9, 'event_id': 805}, {'value': 10, 'event_id': 4889}, {'value': 12, 'event_id': 3158}, {'value': 14, 'event_id': 1374}, {'value': 12, 'event_id': 2921}, {'value': 6, 'event_id': 3337}, {'value': 9, 'event_id': 1964}, {'value': 8, 'event_id': 1784}, {'value': 7, 'event_id': 1721}, {'value': 7, 'event_id': 1606}, {'value': 14, 'event_id': 3867}, {'value': 9, 'event_id': 438}, {'value': 7, 'event_id': 4766}, {'value': 17, 'event_id': 1261}, {'value': 10, 'event_id': 810}, {'value': 5, 'event_id': 3166}, {'value': 9, 'event_id': 3626}, {'value': 8, 'event_id': 3437}, {'value': 7, 'event_id': 3515}, {'value': 10, 'event_id': 889}, {'value': 8, 'event_id': 3377}, {'value': 16, 'event_id': 683}, {'value': 21, 'event_id': 869}, {'value': 14, 'event_id': 1094}, {'value': 7, 'event_id': 790}, {'value': 9, 'event_id': 2450}, {'value': 8, 'event_id': 4866}, {'value': 9, 'event_id': 4148}, {'value': 17, 'event_id': 725}, {'value': 5, 'event_id': 1483}, {'value': 10, 'event_id': 1831}, {'value': 9, 'event_id': 3960}, {'value': 10, 'event_id': 3576}, {'value': 6, 'event_id': 2984}, {'value': 11, 'event_id': 4122}, {'value': 13, 'event_id': 945}, {'value': 8, 'event_id': 2366}, {'value': 8, 'event_id': 1902}, {'value': 13, 'event_id': 2968}, {'value': 10, 'event_id': 2447}, {'value': 3, 'event_id': 1840}, {'value': 10, 'event_id': 4179}, {'value': 10, 'event_id': 4748}, {'value': 13, 'event_id': 70}, {'value': 10, 'event_id': 4412}, {'value': 10, 'event_id': 4408}, {'value': 10, 'event_id': 4873}, {'value': 10, 'event_id': 1962}, {'value': 4, 'event_id': 149}, {'value': 7, 'event_id': 3453}, {'value': 9, 'event_id': 3618}, {'value': 9, 'event_id': 633}, {'value': 10, 'event_id': 3729}, {'value': 15, 'event_id': 3194}, {'value': 15, 'event_id': 1564}, {'value': 9, 'event_id': 4796}, {'value': 10, 'event_id': 443}, {'value': 11, 'event_id': 549}, {'value': 8, 'event_id': 2341}, {'value': 5, 'event_id': 463}, {'value': 12, 'event_id': 2486}, {'value': 11, 'event_id': 298}, {'value': 7, 'event_id': 1222}, {'value': 11, 'event_id': 3841}, {'value': 4, 'event_id': 718}, {'value': 10, 'event_id': 144}, {'value': 15, 'event_id': 505}, {'value': 10, 'event_id': 1654}, {'value': 14, 'event_id': 84}, {'value': 10, 'event_id': 705}, {'value': 8, 'event_id': 1897}, {'value': 11, 'event_id': 1181}, {'value': 13, 'event_id': 4528}, {'value': 9, 'event_id': 4885}, {'value': 9, 'event_id': 999}, {'value': 7, 'event_id': 3899}, {'value': 14, 'event_id': 308}, {'value': 11, 'event_id': 648}, {'value': 9, 'event_id': 23}, {'value': 10, 'event_id': 4382}, {'value': 11, 'event_id': 4849}, {'value': 15, 'event_id': 817}, {'value': 10, 'event_id': 3727}, {'value': 14, 'event_id': 670}, {'value': 6, 'event_id': 912}, {'value': 11, 'event_id': 4470}, {'value': 8, 'event_id': 2029}, {'value': 6, 'event_id': 1877}, {'value': 6, 'event_id': 2005}, {'value': 9, 'event_id': 1886}, {'value': 14, 'event_id': 214}, {'value': 6, 'event_id': 1614}, {'value': 9, 'event_id': 2133}, {'value': 11, 'event_id': 2521}, {'value': 8, 'event_id': 4225}, {'value': 9, 'event_id': 205}, {'value': 11, 'event_id': 2642}, {'value': 7, 'event_id': 1746}, {'value': 11, 'event_id': 3865}, {'value': 19, 'event_id': 1228}, {'value': 9, 'event_id': 2658}, {'value': 4, 'event_id': 2955}, {'value': 16, 'event_id': 1123}, {'value': 11, 'event_id': 3722}, {'value': 14, 'event_id': 192}, {'value': 8, 'event_id': 2647}, {'value': 8, 'event_id': 2093}, {'value': 10, 'event_id': 3065}, {'value': 20, 'event_id': 416}, {'value': 8, 'event_id': 2225}, {'value': 10, 'event_id': 4464}, {'value': 8, 'event_id': 2847}, {'value': 14, 'event_id': 490}, {'value': 9, 'event_id': 2812}, {'value': 12, 'event_id': 3193}, {'value': 9, 'event_id': 4903}, {'value': 10, 'event_id': 2594}, {'value': 7, 'event_id': 3013}, {'value': 10, 'event_id': 4959}, {'value': 11, 'event_id': 29}, {'value': 10, 'event_id': 903}, {'value': 10, 'event_id': 2574}, {'value': 11, 'event_id': 1666}, {'value': 7, 'event_id': 3519}, {'value': 9, 'event_id': 3750}, {'value': 10, 'event_id': 2420}, {'value': 12, 'event_id': 1595}, {'value': 15, 'event_id': 540}, {'value': 6, 'event_id': 69}, {'value': 9, 'event_id': 2662}, {'value': 14, 'event_id': 373}, {'value': 9, 'event_id': 220}, {'value': 8, 'event_id': 2669}, {'value': 10, 'event_id': 1330}, {'value': 4, 'event_id': 321}, {'value': 13, 'event_id': 944}, {'value': 17, 'event_id': 3143}, {'value': 12, 'event_id': 2520}, {'value': 27, 'event_id': 2995}, {'value': 8, 'event_id': 2845}, {'value': 5, 'event_id': 1477}, {'value': 8, 'event_id': 2354}, {'value': 17, 'event_id': 468}, {'value': 6, 'event_id': 2952}, {'value': 9, 'event_id': 1419}, {'value': 10, 'event_id': 3752}, {'value': 13, 'event_id': 589}, {'value': 10, 'event_id': 544}, {'value': 6, 'event_id': 2615}, {'value': 18, 'event_id': 1407}, {'value': 7, 'event_id': 325}, {'value': 7, 'event_id': 3656}, {'value': 20, 'event_id': 744}, {'value': 8, 'event_id': 4329}, {'value': 6, 'event_id': 1730}, {'value': 11, 'event_id': 1321}, {'value': 9, 'event_id': 3827}, {'value': 9, 'event_id': 2387}, {'value': 10, 'event_id': 14}, {'value': 10, 'event_id': 2123}, {'value': 12, 'event_id': 871}, {'value': 7, 'event_id': 45}, {'value': 10, 'event_id': 2131}, {'value': 5, 'event_id': 332}, {'value': 8, 'event_id': 1732}, {'value': 11, 'event_id': 3555}, {'value': 9, 'event_id': 3880}, {'value': 7, 'event_id': 1697}, {'value': 11, 'event_id': 4927}, {'value': 21, 'event_id': 478}, {'value': 10, 'event_id': 2707}, {'value': 12, 'event_id': 291}, {'value': 6, 'event_id': 2623}, {'value': 8, 'event_id': 2269}, {'value': 9, 'event_id': 2457}, {'value': 8, 'event_id': 2570}, {'value': 9, 'event_id': 2488}, {'value': 11, 'event_id': 4585}, {'value': 12, 'event_id': 622}, {'value': 15, 'event_id': 759}, {'value': 8, 'event_id': 3296}, {'value': 7, 'event_id': 653}, {'value': 16, 'event_id': 3169}, {'value': 9, 'event_id': 457}, {'value': 6, 'event_id': 3972}, {'value': 10, 'event_id': 4518}, {'value': 18, 'event_id': 360}, {'value': 9, 'event_id': 4350}, {'value': 22, 'event_id': 270}, {'value': 6, 'event_id': 4196}, {'value': 4, 'event_id': 305}, {'value': 9, 'event_id': 1074}, {'value': 11, 'event_id': 4640}, {'value': 9, 'event_id': 4875}, {'value': 7, 'event_id': 4200}, {'value': 7, 'event_id': 3375}, {'value': 10, 'event_id': 2458}, {'value': 8, 'event_id': 3162}, {'value': 11, 'event_id': 4247}, {'value': 8, 'event_id': 3024}, {'value': 5, 'event_id': 4750}, {'value': 9, 'event_id': 8}, {'value': 12, 'event_id': 4638}, {'value': 19, 'event_id': 582}, {'value': 9, 'event_id': 3612}, {'value': 14, 'event_id': 4048}, {'value': 9, 'event_id': 2170}, {'value': 3, 'event_id': 3497}, {'value': 10, 'event_id': 2940}, {'value': 11, 'event_id': 3126}, {'value': 8, 'event_id': 2115}, {'value': 7, 'event_id': 1869}, {'value': 11, 'event_id': 1782}, {'value': 15, 'event_id': 888}, {'value': 10, 'event_id': 1835}, {'value': 16, 'event_id': 1057}, {'value': 7, 'event_id': 4103}, {'value': 10, 'event_id': 99}, {'value': 4, 'event_id': 44}, {'value': 9, 'event_id': 618}, {'value': 6, 'event_id': 1888}, {'value': 10, 'event_id': 1351}, {'value': 12, 'event_id': 877}, {'value': 6, 'event_id': 4260}, {'value': 10, 'event_id': 4447}, {'value': 14, 'event_id': 95}, {'value': 5, 'event_id': 2218}, {'value': 5, 'event_id': 2822}, {'value': 16, 'event_id': 4662}, {'value': 19, 'event_id': 4700}, {'value': 11, 'event_id': 4921}, {'value': 11, 'event_id': 4577}, {'value': 6, 'event_id': 3659}, {'value': 9, 'event_id': 2473}, {'value': 10, 'event_id': 996}, {'value': 8, 'event_id': 1765}, {'value': 8, 'event_id': 3676}, {'value': 7, 'event_id': 4040}, {'value': 16, 'event_id': 1157}, {'value': 7, 'event_id': 802}, {'value': 6, 'event_id': 3761}, {'value': 7, 'event_id': 3012}, {'value': 9, 'event_id': 1932}, {'value': 10, 'event_id': 1103}, {'value': 8, 'event_id': 65}, {'value': 4, 'event_id': 964}, {'value': 7, 'event_id': 1610}, {'value': 9, 'event_id': 1068}, {'value': 19, 'event_id': 2988}, {'value': 21, 'event_id': 1264}, {'value': 9, 'event_id': 3638}, {'value': 17, 'event_id': 494}, {'value': 10, 'event_id': 2697}, {'value': 15, 'event_id': 1288}, {'value': 5, 'event_id': 1119}, {'value': 9, 'event_id': 3634}, {'value': 13, 'event_id': 4181}, {'value': 8, 'event_id': 2379}, {'value': 10, 'event_id': 1189}, {'value': 9, 'event_id': 3316}, {'value': 5, 'event_id': 4781}, {'value': 12, 'event_id': 2942}, {'value': 9, 'event_id': 113}, {'value': 9, 'event_id': 3720}, {'value': 10, 'event_id': 2929}, {'value': 19, 'event_id': 256}, {'value': 11, 'event_id': 2810}, {'value': 9, 'event_id': 3403}, {'value': 10, 'event_id': 4248}, {'value': 10, 'event_id': 4295}, {'value': 11, 'event_id': 4878}, {'value': 7, 'event_id': 1752}, {'value': 8, 'event_id': 1630}, {'value': 7, 'event_id': 2342}, {'value': 5, 'event_id': 828}, {'value': 10, 'event_id': 3386}, {'value': 12, 'event_id': 3268}, {'value': 9, 'event_id': 794}, {'value': 5, 'event_id': 2550}, {'value': 7, 'event_id': 51}, {'value': 8, 'event_id': 3665}, {'value': 5, 'event_id': 517}, {'value': 15, 'event_id': 90}, {'value': 5, 'event_id': 829}, {'value': 10, 'event_id': 387}, {'value': 8, 'event_id': 543}, {'value': 11, 'event_id': 4549}, {'value': 23, 'event_id': 501}, {'value': 12, 'event_id': 4287}, {'value': 8, 'event_id': 2111}, {'value': 6, 'event_id': 1867}, {'value': 4, 'event_id': 3651}, {'value': 10, 'event_id': 931}, {'value': 9, 'event_id': 647}, {'value': 7, 'event_id': 248}, {'value': 12, 'event_id': 2536}, {'value': 7, 'event_id': 1501}, {'value': 9, 'event_id': 3780}, {'value': 12, 'event_id': 4882}, {'value': 9, 'event_id': 4884}, {'value': 11, 'event_id': 765}, {'value': 13, 'event_id': 356}, {'value': 10, 'event_id': 803}, {'value': 13, 'event_id': 2895}, {'value': 11, 'event_id': 1995}, {'value': 9, 'event_id': 693}, {'value': 7, 'event_id': 1718}, {'value': 14, 'event_id': 3221}, {'value': 10, 'event_id': 4160}, {'value': 9, 'event_id': 2807}, {'value': 6, 'event_id': 1210}, {'value': 8, 'event_id': 3604}, {'value': 12, 'event_id': 3231}, {'value': 16, 'event_id': 4629}, {'value': 5, 'event_id': 4502}, {'value': 14, 'event_id': 3181}, {'value': 9, 'event_id': 2282}, {'value': 9, 'event_id': 2672}, {'value': 5, 'event_id': 4041}, {'value': 8, 'event_id': 1192}, {'value': 10, 'event_id': 1905}, {'value': 8, 'event_id': 4228}, {'value': 7, 'event_id': 2226}, {'value': 9, 'event_id': 1340}, {'value': 3, 'event_id': 1024}, {'value': 9, 'event_id': 3071}, {'value': 24, 'event_id': 3935}, {'value': 10, 'event_id': 2804}, {'value': 9, 'event_id': 896}, {'value': 7, 'event_id': 4332}, {'value': 11, 'event_id': 2197}, {'value': 14, 'event_id': 180}, {'value': 9, 'event_id': 19}, {'value': 12, 'event_id': 506}, {'value': 17, 'event_id': 2943}, {'value': 20, 'event_id': 3257}, {'value': 9, 'event_id': 2389}, {'value': 8, 'event_id': 2254}, {'value': 8, 'event_id': 2561}, {'value': 17, 'event_id': 2876}, {'value': 12, 'event_id': 3759}, {'value': 10, 'event_id': 2127}, {'value': 10, 'event_id': 3227}, {'value': 11, 'event_id': 1162}, {'value': 17, 'event_id': 4098}, {'value': 10, 'event_id': 3782}, {'value': 10, 'event_id': 2439}, {'value': 7, 'event_id': 3894}, {'value': 12, 'event_id': 4826}, {'value': 18, 'event_id': 4649}, {'value': 11, 'event_id': 2316}, {'value': 12, 'event_id': 2465}, {'value': 7, 'event_id': 4194}, {'value': 11, 'event_id': 2515}, {'value': 10, 'event_id': 4550}, {'value': 9, 'event_id': 2585}, {'value': 10, 'event_id': 4243}, {'value': 11, 'event_id': 2505}, {'value': 6, 'event_id': 2957}, {'value': 15, 'event_id': 887}, {'value': 8, 'event_id': 3098}, {'value': 9, 'event_id': 4516}, {'value': 14, 'event_id': 1197}, {'value': 7, 'event_id': 4430}, {'value': 14, 'event_id': 1135}, {'value': 11, 'event_id': 1108}, {'value': 7, 'event_id': 1417}, {'value': 6, 'event_id': 3210}, {'value': 11, 'event_id': 3792}, {'value': 17, 'event_id': 4083}, {'value': 4, 'event_id': 3412}, {'value': 14, 'event_id': 3956}, {'value': 15, 'event_id': 1293}, {'value': 15, 'event_id': 4663}, {'value': 6, 'event_id': 3501}, {'value': 9, 'event_id': 3670}, {'value': 8, 'event_id': 1893}, {'value': 9, 'event_id': 2107}, {'value': 9, 'event_id': 4850}, {'value': 9, 'event_id': 4333}, {'value': 9, 'event_id': 1623}, {'value': 11, 'event_id': 3649}, {'value': 12, 'event_id': 2714}, {'value': 9, 'event_id': 3852}, {'value': 11, 'event_id': 3922}, {'value': 19, 'event_id': 642}, {'value': 8, 'event_id': 2710}, {'value': 9, 'event_id': 2080}, {'value': 5, 'event_id': 2011}, {'value': 10, 'event_id': 3001}, {'value': 11, 'event_id': 1822}, {'value': 7, 'event_id': 2244}, {'value': 5, 'event_id': 691}, {'value': 14, 'event_id': 564}, {'value': 7, 'event_id': 233}, {'value': 9, 'event_id': 862}, {'value': 22, 'event_id': 1061}, {'value': 6, 'event_id': 1432}, {'value': 11, 'event_id': 228}, {'value': 10, 'event_id': 4161}, {'value': 14, 'event_id': 2892}, {'value': 9, 'event_id': 2384}, {'value': 7, 'event_id': 2329}, {'value': 8, 'event_id': 1740}, {'value': 9, 'event_id': 2432}, {'value': 7, 'event_id': 4812}, {'value': 7, 'event_id': 3529}, {'value': 10, 'event_id': 2705}, {'value': 18, 'event_id': 432}, {'value': 14, 'event_id': 527}, {'value': 11, 'event_id': 322}, {'value': 8, 'event_id': 1558}, {'value': 19, 'event_id': 2887}, {'value': 10, 'event_id': 471}, {'value': 10, 'event_id': 2487}, {'value': 8, 'event_id': 1751}, {'value': 13, 'event_id': 561}, {'value': 9, 'event_id': 4357}, {'value': 14, 'event_id': 4004}, {'value': 16, 'event_id': 3253}, {'value': 11, 'event_id': 798}, {'value': 11, 'event_id': 3779}, {'value': 2, 'event_id': 1505}, {'value': 11, 'event_id': 2182}, {'value': 8, 'event_id': 3817}, {'value': 10, 'event_id': 893}, {'value': 7, 'event_id': 2614}, {'value': 9, 'event_id': 2086}, {'value': 12, 'event_id': 567}, {'value': 4, 'event_id': 1480}, {'value': 15, 'event_id': 1281}, {'value': 13, 'event_id': 4118}, {'value': 7, 'event_id': 1723}, {'value': 11, 'event_id': 3815}, {'value': 7, 'event_id': 4610}, {'value': 5, 'event_id': 43}, {'value': 7, 'event_id': 134}, {'value': 7, 'event_id': 3983}, {'value': 9, 'event_id': 2264}, {'value': 10, 'event_id': 3277}, {'value': 9, 'event_id': 4571}, {'value': 6, 'event_id': 3350}, {'value': 11, 'event_id': 1051}, {'value': 9, 'event_id': 4898}, {'value': 7, 'event_id': 2018}, {'value': 10, 'event_id': 2154}, {'value': 14, 'event_id': 170}, {'value': 10, 'event_id': 2748}, {'value': 5, 'event_id': 3333}, {'value': 10, 'event_id': 1807}, {'value': 7, 'event_id': 1323}, {'value': 7, 'event_id': 3362}, {'value': 9, 'event_id': 2287}, {'value': 9, 'event_id': 4371}, {'value': 16, 'event_id': 354}, {'value': 4, 'event_id': 2900}, {'value': 7, 'event_id': 4229}, {'value': 6, 'event_id': 2787}, {'value': 9, 'event_id': 2634}, {'value': 8, 'event_id': 2259}, {'value': 10, 'event_id': 3635}, {'value': 9, 'event_id': 4101}, {'value': 11, 'event_id': 4881}, {'value': 15, 'event_id': 4168}, {'value': 13, 'event_id': 1507}, {'value': 12, 'event_id': 4709}, {'value': 12, 'event_id': 2758}, {'value': 10, 'event_id': 4149}, {'value': 11, 'event_id': 1370}, {'value': 8, 'event_id': 2347}, {'value': 8, 'event_id': 2299}, {'value': 8, 'event_id': 3667}, {'value': 13, 'event_id': 1220}, {'value': 9, 'event_id': 809}, {'value': 15, 'event_id': 1242}, {'value': 6, 'event_id': 2223}, {'value': 10, 'event_id': 2471}, {'value': 13, 'event_id': 274}, {'value': 11, 'event_id': 3112}, {'value': 6, 'event_id': 2346}, {'value': 10, 'event_id': 2698}, {'value': 13, 'event_id': 3142}, {'value': 5, 'event_id': 4217}, {'value': 11, 'event_id': 1272}, {'value': 8, 'event_id': 4270}, {'value': 10, 'event_id': 2194}, {'value': 12, 'event_id': 1129}, {'value': 9, 'event_id': 3447}, {'value': 10, 'event_id': 2483}, {'value': 9, 'event_id': 1912}, {'value': 7, 'event_id': 2569}, {'value': 8, 'event_id': 2233}, {'value': 10, 'event_id': 2819}, {'value': 7, 'event_id': 3662}, {'value': 11, 'event_id': 535}, {'value': 7, 'event_id': 4392}, {'value': 18, 'event_id': 1235}, {'value': 11, 'event_id': 4705}, {'value': 9, 'event_id': 2121}, {'value': 11, 'event_id': 4613}, {'value': 10, 'event_id': 1244}, {'value': 11, 'event_id': 2517}, {'value': 11, 'event_id': 1966}, {'value': 6, 'event_id': 1180}, {'value': 8, 'event_id': 4338}, {'value': 10, 'event_id': 1362}, {'value': 12, 'event_id': 3199}, {'value': 18, 'event_id': 1146}, {'value': 12, 'event_id': 1172}, {'value': 16, 'event_id': 1485}, {'value': 11, 'event_id': 3398}, {'value': 11, 'event_id': 4803}, {'value': 17, 'event_id': 290}, {'value': 14, 'event_id': 2213}, {'value': 10, 'event_id': 800}, {'value': 9, 'event_id': 1747}, {'value': 19, 'event_id': 33}, {'value': 8, 'event_id': 1873}, {'value': 14, 'event_id': 4616}, {'value': 7, 'event_id': 211}, {'value': 17, 'event_id': 3139}, {'value': 6, 'event_id': 1305}, {'value': 11, 'event_id': 2210}, {'value': 8, 'event_id': 1115}, {'value': 9, 'event_id': 3804}, {'value': 7, 'event_id': 1871}, {'value': 14, 'event_id': 881}, {'value': 7, 'event_id': 100}, {'value': 6, 'event_id': 1891}, {'value': 7, 'event_id': 402}, {'value': 10, 'event_id': 199}, {'value': 12, 'event_id': 2174}, {'value': 8, 'event_id': 4204}, {'value': 8, 'event_id': 1909}, {'value': 8, 'event_id': 4601}, {'value': 13, 'event_id': 1519}, {'value': 9, 'event_id': 1924}, {'value': 9, 'event_id': 4791}, {'value': 9, 'event_id': 4403}, {'value': 10, 'event_id': 4956}, {'value': 10, 'event_id': 1832}, {'value': 10, 'event_id': 3046}, {'value': 5, 'event_id': 3928}, {'value': 13, 'event_id': 203}, {'value': 8, 'event_id': 4331}, {'value': 14, 'event_id': 1097}, {'value': 11, 'event_id': 106}, {'value': 13, 'event_id': 4929}, {'value': 13, 'event_id': 3119}, {'value': 9, 'event_id': 2238}, {'value': 12, 'event_id': 676}, {'value': 23, 'event_id': 314}, {'value': 11, 'event_id': 3712}, {'value': 15, 'event_id': 4088}, {'value': 14, 'event_id': 2820}, {'value': 6, 'event_id': 4219}, {'value': 9, 'event_id': 4922}, {'value': 11, 'event_id': 1497}, {'value': 8, 'event_id': 1626}, {'value': 11, 'event_id': 188}, {'value': 7, 'event_id': 2369}, {'value': 15, 'event_id': 415}, {'value': 18, 'event_id': 1378}, {'value': 8, 'event_id': 3813}, {'value': 10, 'event_id': 576}, {'value': 10, 'event_id': 2462}, {'value': 6, 'event_id': 2954}, {'value': 11, 'event_id': 4006}, {'value': 12, 'event_id': 598}, {'value': 10, 'event_id': 4714}, {'value': 9, 'event_id': 3523}, {'value': 4, 'event_id': 4104}, {'value': 6, 'event_id': 4220}, {'value': 3, 'event_id': 238}, {'value': 8, 'event_id': 1629}, {'value': 5, 'event_id': 3652}, {'value': 7, 'event_id': 3442}, {'value': 9, 'event_id': 3312}, {'value': 18, 'event_id': 426}, {'value': 10, 'event_id': 2644}, {'value': 7, 'event_id': 833}, {'value': 9, 'event_id': 2905}, {'value': 11, 'event_id': 2468}, {'

In [ ]:
utils.write_ground_truth(boto_session, ground_truths_to_submit, p.ground_truth_dir, created_at=datetime.datetime.now(datetime.timezone.utc))

# s3://omm-test-bucket/models/abalone/data/ground-truth/2026/05/21/19/03-55-055216.jsonl
# {
#   "groundTruthData": {
#     "data": "5",
#     "encoding": "CSV"
#   },
#   "eventMetadata": {
#     "eventId": 4163
#   },
#   "eventVersion": "0"
# }
# {
#   "groundTruthData": {
#     "data": "12",
#     "encoding": "CSV"
#   },
#   "eventMetadata": {
#     "eventId": 1270
#   },
#   "eventVersion": "0"
# }