In [38]:
import sys
if '/home/ec2-user/sagemaker-pipe-template' not in sys.path:
    sys.path.insert(0, '/home/ec2-user/sagemaker-pipe-template')
import utils
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import pandas as pd
import sagemaker, boto3, os
import paths, utils
from utils import Sql, train_val_test_split, get_sm_service_role_arn
import sagemaker.core.helper.session_helper as sm_session_helper
import sagemaker.core.inputs as sm_inputs
import sagemaker.core.image_uris as sm_image_uris
import sagemaker.train.model_trainer as sm_model_trainer
from sagemaker.core.training import configs as sm_train_configs
import sagemaker.core.shapes as sm_shapes

In [39]:
# User vars
region = 'us-east-1'
model_package_group_name='abalone'
model_version=1
target_name='rings'
prediction_name=target_name+'_prediction'

p=paths.Paths(bucket_name='omm-test-bucket', project_name='abalone', model_prefix='abalone')
role = get_sm_service_role_arn()
boto_session=boto3.Session(region_name=region)
sagemaker_session = sm_session_helper.Session(boto_session=boto_session)

[06/14/26 23:12:46] INFO     Found credentials from IAM      ]8;id=3572027;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=3572028;file:///home/ec2-user/.local/lib/python3.9/site-packages/botocore/credentials.py#1171\1171]8;;\
                             Role: ec2-1

In [40]:
# DATA INGESTION
sql=Sql('user-1', 'password', 'db_1')
abalone_df = sql.query('SELECT * FROM abalone;')
abalone_df=abalone_df.drop(columns=['id','created_at'])

In [41]:
# FEATURE ENGINEERING
abalone_df = pd.get_dummies(abalone_df, columns=['sex'], drop_first=False)
abalone_df[['sex_I', 'sex_M', 'sex_F']] = abalone_df[['sex_I', 'sex_M', 'sex_F']].astype(int)
abalone_df.head()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings,sex_F,sex_I,sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15,0,0,1
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7,0,0,1
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9,1,0,0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10,0,0,1
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7,0,1,0

In [ ]:
# DATA FORMATTING
y = abalone_df['rings']
X = abalone_df.drop(columns=['rings'])

X_train, X_val, X_test, y_train, y_val, y_test = train_val_test_split(X, y, train_size=0.7, val_size=0.15, random_state=42)

pd.concat([y_train, X_train], axis=1).to_csv(p.train_file, index=False, header=False)
pd.concat([y_val, X_val], axis=1).to_csv(p.validation_file, index=False, header=False)
pd.concat([y_test, X_test], axis=1).to_csv(p.test_file, index=False, header=False)
pd.concat([y_val, X_val], axis=1).to_csv(p.baseline_file, index=False, header=True) # need header

# For development and testing
X_test.to_csv(p.test_X_file, index=True, header=False)
y_test.to_csv(p.test_y_file, index=True, header=False)

input_data = {
    'train': sm_inputs.TrainingInput(p.train_dir+'/', content_type='text/csv'),
    'validation': sm_inputs.TrainingInput(p.validation_dir+'/', content_type='text/csv'),
    # xgboost only accepts train and validation 'test': sm_inputs.TrainingInput(test_s3_dir+'/', content_type='text/csv')
}

input_data_config = [
    sm_train_configs.InputData(channel_name='train', data_source=p.train_dir),
    sm_train_configs.InputData(channel_name='validation', data_source=p.validation_dir)
]

In [36]:
model_trainer = sm_model_trainer.ModelTrainer(
    training_image=sm_image_uris.retrieve('xgboost', region, version='1.5-1'),
    hyperparameters={
        'objective': 'reg:squarederror',
        'num_round': '100',
        'max_depth': '5',
        'eta': '0.2',
        'subsample': '0.8',
        'eval_metric': 'rmse'
    },
    role=role,
    sagemaker_session=sagemaker_session,
    base_job_name='abalone-train-job',
    output_data_config=sm_shapes.OutputDataConfig(s3_output_path=p.model_dir),
    networking=sm_train_configs.Networking(
        subnets=['subnet-001be661bcef4b615', 'subnet-003ad32933ca43e74'],
        security_group_ids=['sg-00f14515abe1e47e8']
    )
)

[06/14/26 23:05:54] INFO     Ignoring unnecessary instance     ]8;id=3571871;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/image_uris.py\image_uris.py]8;;\:]8;id=3571872;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/image_uris.py#535\535]8;;\
                             type: None.

                    INFO     Compute not provided. Using         ]8;id=3571877;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=3571878;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py#102\102]8;;\
                             default:
                             instance_type='ml.m5.xlarge'
                             instance_count=1
                             volume_size_in_gb=30
                             volume_kms_key_id=None
                             keep_alive_period_in_seconds=None
                             instance_groups=None
                             training_plan_arn=None
                             instance_placement_config=None
                             enable_managed_spot_training=None
                    INFO     StoppingCondition not provided.     ]8;id=3571883;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=3571884;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/defaults.py#128\128]8;;\
                             Using default:
                             max_runtime_in_seconds=3600
                             max_wait_time_in_seconds=None
                             max_pending_time_in_seconds=None
                    INFO     Training image URI:            ]8;id=3571889;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/model_trainer.py\model_trainer.py]8;;\:]8;id=3571890;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/train/model_trainer.py#558\558]8;;\
                             683313688378.dkr.ecr.us-east-1
                             .amazonaws.com/sagemaker-xgboo
                             st:1.5-1

In [37]:
training_job = model_trainer.train(
    input_data_config=input_data_config,
    wait=True,
    logs=True
)

[06/14/26 23:05:57] INFO     SageMaker Python SDK will  ]8;id=3571895;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=3571896;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/telemetry/telemetry_logging.py#110\110]8;;\
                             collect telemetry to help
                             us better understand our
                             user's needs, diagnose
                             issues, and deliver
                             additional features.
                             To opt out of telemetry,
                             please disable via
                             TelemetryOptOut parameter
                             in SDK defaults config.
                             For more information,
                             refer to
                             https://sagemaker.readthed
                             ocs.io/en/stable/overview.
                             html#configuring-and-using
                             -defaults-with-the-sagemak
                             er-python-sdk.
                    INFO     Creating training_job resource.  ]8;id=3571901;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=3571902;file:///home/ec2-user/.local/lib/python3.9/site-packages/sagemaker/core/resources.py#31116\31116]8;;\
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:00                                    │
│ ⠋ Current status:                                                            │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:00                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:00                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:00                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:01                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:01                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:01                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:01                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:02                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:02                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:02                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:02                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:03                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:03                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:03                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:03                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:04                                    │
│ ⠋ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:04                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:04                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:04                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:05                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:05                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:05                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:05                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:06                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:06                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:06                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:06                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:07                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:07                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:07                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:07                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:08                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:08                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:08                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:08                                    │
│ ⠋ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:09                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:09                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:09                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:09                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:10                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:10                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:10                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:10                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:11                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:11                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:11                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:11                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:12                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:12                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:12                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:12                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:13                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:13                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:13                                    │
│ ⠋ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:13                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:14                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:14                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:14                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:14                                    │
│ ⠦ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:15                                    │
│ ⠏ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:15                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:15                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=== ] Waiting for TrainingJob... 0:00:15                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:16                                    │
│ ⠹ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:16                                    │
│ ⠴ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:16                                    │
│ ⠇ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:16                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [ ===] Waiting for TrainingJob... 0:00:17                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [    ] Waiting for TrainingJob... 0:00:17                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:17                                    │
│ ⠙ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [=   ] Waiting for TrainingJob... 0:00:17                                    │
│ ⠼ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [==  ] Waiting for TrainingJob... 0:00:18                                    │
│ ⠧ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [  ==] Waiting for TrainingJob... 0:00:18                                    │
│ ⠋ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [   =] Waiting for TrainingJob... 0:00:18                                    │
│ ⠸ Current status: InProgress                                                 │
╭─────────────────────────────── Wait Log Panel ───────────────────────────────╮
│ [====] Waiting for TrainingJob... 0:00:18                                    │
│ ⠦ Current status: InProgress                                                 │

FailedStatusError: Encountered unexpected failed state while waiting for TrainingJob. Final Resource State: Failed. Failure Reason: AlgorithmError: framework error:
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 102, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 98, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 64, in run_algorithm_mode
    sagemaker_train(
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 198, in sagemaker_train
    train_dmatrix, val_dmatrix, train_val_dmatrix = get_validated_dmatrices(
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 78, in get_validated_dmatrices
    validate_data_file_path(train_path, content_type)
  File "/miniconda

In [33]:
model_trainer = sm_model_trainer.ModelTrainer(
    training_mode=sm_model_trainer.Mode.SAGEMAKER_TRAINING_JOB,
    training_image=sm_image_uris.retrieve('xgboost', region, version='1.5-1'),
    hyperparameters = {
        'objective': 'reg:squarederror',  # for regression (abalone rings)
        'num_round': '100',               # REQUIRED - number of boosting rounds
    },
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    output_data_config=sm_shapes.OutputDataConfig(s3_output_path=p.model_dir),
    networking=sm_train_configs.Networking(
        subnets=['subnet-001be661bcef4b615', 'subnet-003ad32933ca43e74'],
        security_group_ids=['sg-00f14515abe1e47e8']
    ),
    input_data_config=sm_train_configs.InputData('train')
    sagemaker_session=sagemaker_session
)

SyntaxError: invalid syntax (1786695786.py, line 17)

In [ ]:



# # TRAINING
# estimator = sagemaker.estimator.Estimator(
#     image_uri=sagemaker.image_uris.retrieve('xgboost', region, version='1.5-1'),
#     role=role,
#     instance_count=1,
#     instance_type='ml.m5.xlarge',
#     output_path=model_dir_uri,
#     sagemaker_session=sagemaker_session,
#     subnets=['subnet-001be661bcef4b615', 'subnet-003ad32933ca43e74'],
#     security_group_ids=['sg-00f14515abe1e47e8']
# )

# Set hyperparameters
estimator.set_hyperparameters(
    objective='reg:squarederror',
    num_round=100
)

# Train
estimator.fit(input_data)
print(estimator.model_data)

/home/ec2-user/.local/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)
INFO:sagemaker:Creating training-job with name: sagemaker-xgboost-2026-05-21-17-07-18-342

2026-05-21 17:07:23 Starting - Starting the training job...
2026-05-21 17:07:41 Starting - Preparing the instances for training...
2026-05-21 17:08:00 Downloading - Downloading input data...
2026-05-21 17:08:26 Downloading - Downloading the training image...
2026-05-21 17:09:12 Training - Training image download completed. Training in progress../miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2026-05-21 17:09:22.455 ip-172-31-108-128.ec2.internal:7 INFO utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2026-05-21 17:09:22.476 ip-172-31-108-128.ec2.internal:7 INFO profiler_config_parser.py:111] User has disabled profiler.
[2026-05-21:17:09:22:INFO] Imported framework sagemaker_xgboost_container.training
[2026-05-21:17:09:22:INFO] Failed to parse hyperparameter objective value reg:squarederror to Json.
Returning the value itself
[2026-05-21:17:09:22:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:09:22:INFO] Running XGBoost Sagemaker in algorithm mode
[2026-05-21:17:09:22:INFO] Determined 0 GPU(s) available on the instance.
[2026-05-21:17:09:22:INFO] Determined delimiter of CSV input is ','
[2026-05-21:17:09:22:INFO] Determined delimiter of CSV input is ','
[2026-05-21:17:09:22:INFO] files path: /opt/ml/input/data/train
[2026-05-21:17:09:22:INFO] Determined delimiter of CSV input is ','
[2026-05-21:17:09:22:INFO] files path: /opt/ml/input/data/validation
[2026-05-21:17:09:22:INFO] Determined delimiter of CSV input is ','
[2026-05-21:17:09:22:INFO] Single node training.
[2026-05-21:17:09:22:INFO] Train matrix has 3474 rows and 10 columns
[2026-05-21:17:09:22:INFO] Validation matrix has 744 rows
[2026-05-21 17:09:22.858 ip-172-31-108-128.ec2.internal:7 INFO json_config.py:92] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.
[2026-05-21 17:09:22.858 ip-172-31-108-128.ec2.internal:7 INFO hook.py:206] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.
[2026-05-21 17:09:22.859 ip-172-31-108-128.ec2.internal:7 INFO hook.py:259] Saving to /opt/ml/output/tensors
[2026-05-21 17:09:22.859 ip-172-31-108-128.ec2.internal:7 INFO state_store.py:77] The checkpoint config file /opt/ml/input/config/checkpointconfig.json does not exist.
[2026-05-21:17:09:22:INFO] Debug hook created from config
[2026-05-21 17:09:22.875 ip-172-31-108-128.ec2.internal:7 INFO hook.py:427] Monitoring the collections: metrics
[2026-05-21 17:09:22.877 ip-172-31-108-128.ec2.internal:7 INFO hook.py:491] Hook is writing from the hook with pid: 7
[0]#011train-rmse:7.40982#011validation-rmse:7.34180
[1]#011train-rmse:5.43800#011validation-rmse:5.35841
[2]#011train-rmse:4.10400#011validation-rmse:4.05660
[3]#011train-rmse:3.22356#011validation-rmse:3.22225
[4]#011train-rmse:2.65419#011validation-rmse:2.71384
[5]#011train-rmse:2.29242#011validation-rmse:2.41306
[6]#011train-rmse:2.07336#011validation-rmse:2.24755
[7]#011train-rmse:1.93363#011validation-rmse:2.15812
[8]#011train-rmse:1.85140#011validation-rmse:2.09726
[9]#011train-rmse:1.80000#011validation-rmse:2.06969
[10]#011train-rmse:1.75563#011validation-rmse:2.03852
[11]#011train-rmse:1.72554#011validation-rmse:2.02477
[12]#011train-rmse:1.70856#011validation-rmse:2.02324
[13]#011train-rmse:1.67992#011validation-rmse:2.02243
[14]#011train-rmse:1.67109#011validation-rmse:2.02231
[15]#011train-rmse:1.64367#011validation-rmse:2.01649
[16]#011train-rmse:1.58858#011validation-rmse:1.99870
[17]#011train-rmse:1.56414#011validation-rmse:1.99538
[18]#011train-rmse:1.55767#011validation-rmse:1.99388
[19]#011train-rmse:1.53608#011validation-rmse:1.99171
[20]#011train-rmse:1.52808#011validation-rmse:1.98866
[21]#011train-rmse:1.50740#011validation-rmse:1.97956
[22]#011train-rmse:1.47071#011validation-rmse:1.97214
[23]#011train-rmse:1.44793#011validation-rmse:1.96379
[24]#011train-rmse:1.42680#011validation-rmse:1.95925
[25]#011train-rmse:1.39273#011validation-rmse:1.95812
[26]#011train-rmse:1.37630#011validation-rmse:1.95891
[27]#011train-rmse:1.37202#011validation-rmse:1.95676
[28]#011train-rmse:1.35161#011validation-rmse:1.95556
[29]#011train-rmse:1.32455#011validation-rmse:1.94997
[30]#011train-rmse:1.30873#011validation-rmse:1.94460
[31]#011train-rmse:1.30590#011validation-rmse:1.94154
[32]#011train-rmse:1.28386#011validation-rmse:1.93427
[33]#011train-rmse:1.27934#011validation-rmse:1.93311
[34]#011train-rmse:1.26063#011validation-rmse:1.93085
[35]#011train-rmse:1.24210#011validation-rmse:1.92355
[36]#011train-rmse:1.22868#011validation-rmse:1.92325
[37]#011train-rmse:1.21995#011validation-rmse:1.91683
[38]#011train-rmse:1.21373#011validation-rmse:1.91638
[39]#011train-rmse:1.20661#011validation-rmse:1.91607
[40]#011train-rmse:1.19825#011validation-rmse:1.91513
[41]#011train-rmse:1.18118#011validation-rmse:1.90997
[42]#011train-rmse:1.16646#011validation-rmse:1.90656
[43]#011train-rmse:1.15779#011validation-rmse:1.91184
[44]#011train-rmse:1.13691#011validation-rmse:1.91513
[45]#011train-rmse:1.12039#011validation-rmse:1.91589
[46]#011train-rmse:1.11917#011validation-rmse:1.91600
[47]#011train-rmse:1.11174#011validation-rmse:1.91637
[48]#011train-rmse:1.10424#011validation-rmse:1.91683
[49]#011train-rmse:1.09543#011validation-rmse:1.91672
[50]#011train-rmse:1.08886#011validation-rmse:1.91725
[51]#011train-rmse:1.07438#011validation-rmse:1.91506
[52]#011train-rmse:1.05636#011validation-rmse:1.91260
[53]#011train-rmse:1.03979#011validation-rmse:1.91679
[54]#011train-rmse:1.03057#011validation-rmse:1.91412
[55]#011train-rmse:1.02908#011validation-rmse:1.91157
[56]#011train-rmse:1.02213#011validation-rmse:1.90677
[57]#011train-rmse:1.01332#011validation-rmse:1.90495
[58]#011train-rmse:1.00422#011validation-rmse:1.90269
[59]#011train-rmse:0.99812#011validation-rmse:1.90348
[60]#011train-rmse:0.98486#011validation-rmse:1.90130
[61]#011train-rmse:0.97170#011validation-rmse:1.90019
[62]#011train-rmse:0.95955#011validation-rmse:1.89637
[63]#011train-rmse:0.95649#011validation-rmse:1.89656
[64]#011train-rmse:0.95347#011validation-rmse:1.89392
[65]#011train-rmse:0.95206#011validation-rmse:1.89283
[66]#011train-rmse:0.94200#011validation-rmse:1.89227
[67]#011train-rmse:0.93250#011validation-rmse:1.89334
[68]#011train-rmse:0.92571#011validation-rmse:1.89515
[69]#011train-rmse:0.91370#011validation-rmse:1.89353
[70]#011train-rmse:0.90107#011validation-rmse:1.89731
[71]#011train-rmse:0.89729#011validation-rmse:1.89719
[72]#011train-rmse:0.88342#011validation-rmse:1.89450
[73]#011train-rmse:0.88214#011validation-rmse:1.89474
[74]#011train-rmse:0.87835#011validation-rmse:1.89550
[75]#011train-rmse:0.86514#011validation-rmse:1.89856
[76]#011train-rmse:0.85573#011validation-rmse:1.89620
[77]#011train-rmse:0.85170#011validation-rmse:1.89461
[78]#011train-rmse:0.84677#011validation-rmse:1.89414
[79]#011train-rmse:0.84434#011validation-rmse:1.89553
[80]#011train-rmse:0.83479#011validation-rmse:1.89264
[81]#011train-rmse:0.82691#011validation-rmse:1.88991
[82]#011train-rmse:0.82074#011validation-rmse:1.88741
[83]#011train-rmse:0.81361#011validation-rmse:1.88422
[84]#011train-rmse:0.80387#011validation-rmse:1.88067
[85]#011train-rmse:0.79780#011validation-rmse:1.88280
[86]#011train-rmse:0.79617#011validation-rmse:1.88245
[87]#011train-rmse:0.79258#011validation-rmse:1.88487
[88]#011train-rmse:0.79102#011validation-rmse:1.88390
[89]#011train-rmse:0.78024#011validation-rmse:1.87949
[90]#011train-rmse:0.76955#011validation-rmse:1.87888
[91]#011train-rmse:0.76122#011validation-rmse:1.87966
[92]#011train-rmse:0.75649#011validation-rmse:1.87946
[93]#011train-rmse:0.74778#011validation-rmse:1.88334
[94]#011train-rmse:0.73870#011validation-rmse:1.88453
[95]#011train-rmse:0.73101#011validation-rmse:1.88764
[96]#011train-rmse:0.72895#011validation-rmse:1.88872
[97]#011train-rmse:0.72361#011validation-rmse:1.88613
[98]#011train-rmse:0.71732#011validation-rmse:1.88731
[99]#011train-rmse:0.71220#011validation-rmse:1.88475

2026-05-21 17:09:40 Uploading - Uploading generated training model
2026-05-21 17:09:40 Completed - Training job completed
Training seconds: 100
Billable seconds: 100
s3://omm-test-bucket/models/abalone/model/sagemaker-xgboost-2026-05-21-17-07-18-342/output/model.tar.gz

In [ ]:
# BASELINING
# get baseline X
baseline=pd.read_csv(p.baseline_file, header=0)
baseline[target_name] = baseline[target_name].astype(float)
baseline_X = baseline.drop(columns=[target_name])
baseline_X.to_csv(p.baseline_X_file, index=False, header=False)

# Get predictions from baseline X
transformer = estimator.transformer(instance_count=1, instance_type='ml.m5.xlarge', output_path=p.temp_data_dir)
transformer.transform(data=p.baseline_X_file, content_type='text/csv', split_type='Line')
transformer.wait()

# Rename/move predictions file
utils.move_s3_file(boto_session, p.baseline_model_out_file, p.baseline_pred_file)

INFO:sagemaker:Creating model with name: sagemaker-xgboost-2026-05-21-17-13-20-923
INFO:sagemaker:Creating transform job with name: sagemaker-xgboost-2026-05-21-17-13-21-446

............................../miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-05-21 17:18:27 +0000] [19] [INFO] Starting gunicorn 19.10.0
[2026-05-21 17:18:27 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2026-05-21 17:18:27 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2026-05-21 17:18:27 +0000] [25] [INFO] Booting worker with pid: 25
[2026-05-21 17:18:27 +0000] [26] [INFO] Booting worker with pid: 26
[2026-05-21 17:18:27 +0000] [27] [INFO] Booting worker with pid: 27
[2026-05-21 17:18:27 +0000] [28] [INFO] Booting worker with pid: 28
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-05-21:17:18:33:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:105: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [21/May/2026:17:18:33 +0000] "POST /invocations HTTP/1.1" 200 13658 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-05-21:17:18:33:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:105: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [21/May/2026:17:18:33 +0000] "POST /invocations HTTP/1.1" 200 13658 "-" "Go-http-client/1.1"
2026-05-21T17:18:32.999:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-05-21 17:18:27 +0000] [19] [INFO] Starting gunicorn 19.10.0
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:27:INFO] nginx config:
worker_processes auto;
daemon off;
pid /tmp/nginx.pid;
error_log  /dev/stderr;
worker_rlimit_nofile 4096;
events {
  worker_connections 2048;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout combined;
  upstream gunicorn {
    server unix:/tmp/gunicorn.sock;
  }
  server {
    listen 8080 deferred;
    client_max_body_size 0;
    keepalive_timeout 3;
    location ~ ^/(ping|invocations|execution-parameters) {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_read_timeout 60s;
      proxy_pass http://gunicorn;
    }
    location / {
      return 404 "{}";
    }
  }
}
[2026-05-21 17:18:27 +0000] [19] [INFO] Starting gunicorn 19.10.0
[2026-05-21 17:18:27 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2026-05-21 17:18:27 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2026-05-21 17:18:27 +0000] [25] [INFO] Booting worker with pid: 25
[2026-05-21 17:18:27 +0000] [26] [INFO] Booting worker with pid: 26
[2026-05-21 17:18:27 +0000] [27] [INFO] Booting worker with pid: 27
[2026-05-21 17:18:27 +0000] [28] [INFO] Booting worker with pid: 28
[2026-05-21 17:18:27 +0000] [19] [INFO] Listening at: unix:/tmp/gunicorn.sock (19)
[2026-05-21 17:18:27 +0000] [19] [INFO] Using worker: gevent
/miniconda3/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2026-05-21 17:18:27 +0000] [25] [INFO] Booting worker with pid: 25
[2026-05-21 17:18:27 +0000] [26] [INFO] Booting worker with pid: 26
[2026-05-21 17:18:27 +0000] [27] [INFO] Booting worker with pid: 27
[2026-05-21 17:18:27 +0000] [28] [INFO] Booting worker with pid: 28
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/miniconda3/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] No GPUs detected (normal if no gpus installed)
[2026-05-21:17:18:30:INFO] Loading the model from /opt/ml/model/xgboost-model
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:30:INFO] Model objective : reg:squarederror
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-05-21:17:18:33:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:105: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [21/May/2026:17:18:33 +0000] "POST /invocations HTTP/1.1" 200 13658 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /ping HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2026-05-21:17:18:32:INFO] No GPUs detected (normal if no gpus installed)
169.254.255.130 - - [21/May/2026:17:18:32 +0000] "GET /execution-parameters HTTP/1.1" 200 84 "-" "Go-http-client/1.1"
[2026-05-21:17:18:33:INFO] Determined delimiter of CSV input is ','
/miniconda3/lib/python3.8/site-packages/xgboost/core.py:105: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(
169.254.255.130 - - [21/May/2026:17:18:33 +0000] "POST /invocations HTTP/1.1" 200 13658 "-" "Go-http-client/1.1"
2026-05-21T17:18:32.999:[sagemaker logs]: MaxConcurrentTransforms=4, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD

,rings_prediction,rings,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,sex_F,sex_I,sex_M
0,8.144435,7.0,0.410,0.30,0.100,0.2820,0.1255,0.057,0.0875,0,1,0
1,12.470012,13.0,0.450,0.36,0.125,0.4995,0.2035,0.100,0.1700,1,0,0
2,9.323292,11.0,0.490,0.38,0.135,0.5415,0.2175,0.095,0.1900,0,0,1
3,10.996564,14.0,0.430,0.34,0.125,0.3840,0.1375,0.061,0.1460,0,1,0
4,10.479134,11.0,0.545,0.45,0.150,0.8795,0.3870,0.150,0.2625,0,0,1

In [ ]:
# Register model from estimator
model = estimator.create_model(name=f"{model_package_group_name}-{str(model_version)}")

model.create(instance_type='ml.m5.large') # temporary instance for validation

model_package = model.register(
    content_types=['text/csv'],
    response_types=['text/csv'],
    inference_instances=['ml.m5.large'],
    transform_instances=['ml.m5.large'],
    model_package_group_name='abalone',
    description='XGBoost model for abalone ring prediction',
    approval_status='PendingManualApproval'  # or 'Approved'
)

INFO:sagemaker:Creating model with name: abalone-1